// app/javascript/react/pages/Chat.tsx
import { useCurrentUser } from '@/react/hooks/currentUser'
import React, { useState, useEffect } from 'react'
import { TwCard, TwInput, TwButton } from '../components/presentational/Tw'
import { useSayMutation, useOnMessageAddedSubscription } from '../graphql'

type Props = {}

type State = {
  text: string
  messages: string[]
}

export const Chat: React.FC<Props> = () => {
  const [text, setText] = useState<string>('')
  const [messages, setMessages] = useState<string[]>([])
  const { currentUser } = useCurrentUser()
  const [mutate, { error, loading }] = useSayMutation({
    variables: {
      input: {
        text: `React: ${text}`,
      },
    },
  })
  const messageAdded = useOnMessageAddedSubscription()
  useEffect(() => {
    const message = messageAdded.data?.onMessageAdded.message
    if (!message) return
    setMessages((oldMessages) => [...oldMessages, message])
  }, [messageAdded.data?.onMessageAdded, setMessages])
  return (
    <>
      <div className="flex flex-col justify-center items-center pt-10">
        <form
          onSubmit={(e) => {
            e.preventDefault()
            mutate()
          }}
        >
          <TwCard>
            <p>This is example chat app!</p>
            Hello {currentUser ? currentUser.email : 'loading'}
            <p className="pt-10">Say!</p>
            <TwInput
              defaultValue={text}
              onChange={(e) => setText(e.target.value)}
            />
            <TwButton className="w-full mt-3" disabled={loading}>
              Submit
            </TwButton>
            {error && <span>{{ error }}</span>}
          </TwCard>
        </form>
        <div className="mt-5">
          {messages.map((message, i) => (
            <p key={i}>{message}</p>
          ))}
        </div>
      </div>
    </>
  )
}

// app/javascript/vue/pages/Chat.vue
<template>
  <div class="flex flex-col justify-center items-center pt-10">
    <form @submit.prevent="mutate">
      <tw-card>
        <p>This is example chat app!</p>
        Hello {{ currentUser ? currentUser.email : 'loading' }}

        <p class="pt-10">Say!</p>
        <tw-input v-model="state.text" />
        <tw-button class="w-full mt-3" :disabled="loading">Submit</tw-button>
      </tw-card>
    </form>
    <div class="mt-5">
      <p v-for="(message, i) in state.messages" :key="i">{{ message }}</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from '@vue/composition-api'
import { useCurrentUser } from '@/vue/hooks/currentUser'
import {
  SayDocument,
  SayMutation,
  SayMutationVariables,
  useOnMessageAddedSubscription
} from '@/graphql/types'
import { useMutation } from '@vue/apollo-composable'

type State = {
  text: string
  messages: string[]
}

export default defineComponent({
  setup() {
    const state = reactive<State>({
      text: '',
      messages: []
    })
    const { currentUser } = useCurrentUser()

    const { mutate, error, loading, onDone } = useMutation<
      SayMutation,
      SayMutationVariables
    >(SayDocument, () => ({
      variables: {
        input: {
          text: state.text
        }
      }
    }))

    const { result, onResult } = useOnMessageAddedSubscription()

    onDone(() => (state.text = ''))
    onResult((result) => {
      const message = result?.data?.onMessageAdded.message
      if (message) {
        state.messages.push(message)
      }
    })

    return { state, currentUser, loading, mutate }
  }
})
</script>

<style scoped></style>
